name: native_api
description: native_api for thesis



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"







dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.3.0
  local_auth: ^2.0.1
  nfc_manager: ^3.1.1


  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^1.0.0





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
